/**
 * synthdata standalone API — accounts + saved datasets for synthdata.testforge-ai.com
 *
 * Endpoints (all JSON):
 *   POST /api/auth/register  {email, password, name}        -> {token, user}
 *   POST /api/auth/login     {email, password}              -> {token, user}
 *   POST /api/auth/forgot    {email}                        -> generic ok (emails reset link)
 *   POST /api/auth/reset     {token, password}              -> ok
 *   GET  /api/me                                    (auth)  -> {user}
 *   POST /api/datasets       {name?, ddl, planYaml?, seed?, rows?, businessCase?} (auth)
 *   GET  /api/datasets                              (auth)  -> {datasets}
 *   GET  /api/datasets/:id/file?format=db|sql       (auth)  -> file (regenerated by seed)
 *   DELETE /api/datasets/:id                        (auth)
 *
 * Env: PORT (default 8791), JWT_SECRET (required in prod), DATA_DIR,
 *      SMTP_HOST/PORT/USER/PASS, MAIL_FROM, PUBLIC_URL
 */
import express from 'express';
import Database from 'better-sqlite3';
import jwt from 'jsonwebtoken';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import YAML from 'yaml';
import { parseDDL } from '../src/schema.js';
import { Engine } from '../src/engine.js';
import { ddlToSqlite } from '../src/export.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PORT = +(process.env.PORT ?? 8791);
const JWT_SECRET = process.env.JWT_SECRET ?? 'dev-secret-change-me';
const DATA_DIR = process.env.DATA_DIR ?? path.join(__dirname, 'data');
const PUBLIC_URL = process.env.PUBLIC_URL ?? 'https://synthdata.testforge-ai.com';

fs.mkdirSync(DATA_DIR, { recursive: true });
const db = new Database(path.join(DATA_DIR, 'synthdata-app.db'));
db.pragma('journal_mode = WAL');
db.exec(`
  CREATE TABLE IF NOT EXISTS users (
    id         TEXT PRIMARY KEY,
    email      TEXT NOT NULL UNIQUE,
    name       TEXT,
    pass_hash  TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  );
  CREATE TABLE IF NOT EXISTS reset_tokens (
    token      TEXT PRIMARY KEY,
    user_id    TEXT NOT NULL REFERENCES users(id),
    expires_at INTEGER NOT NULL,
    used       INTEGER NOT NULL DEFAULT 0
  );
  CREATE TABLE IF NOT EXISTS datasets (
    id            TEXT PRIMARY KEY,
    user_id       TEXT NOT NULL REFERENCES users(id),
    name          TEXT NOT NULL,
    ddl           TEXT NOT NULL,
    business_case TEXT,
    plan_yaml     TEXT NOT NULL,
    seed          INTEGER NOT NULL DEFAULT 42,
    tables_count  INTEGER NOT NULL,
    rows_count    INTEGER NOT NULL,
    created_at    TEXT NOT NULL DEFAULT (datetime('now'))
  );
  CREATE INDEX IF NOT EXISTS idx_datasets_user ON datasets(user_id, created_at DESC);
`);

/* ---------- passwords (scrypt, no native deps) ---------- */
const hashPassword = (pw) => {
  const salt = crypto.randomBytes(16).toString('hex');
  const hash = crypto.scryptSync(pw, salt, 64).toString('hex');
  return `${salt}:${hash}`;
};
const verifyPassword = (pw, stored) => {
  const [salt, hash] = stored.split(':');
  const test = crypto.scryptSync(pw, salt, 64).toString('hex');
  return crypto.timingSafeEqual(Buffer.from(hash, 'hex'), Buffer.from(test, 'hex'));
};

/* ---------- email (nodemailer if configured, console fallback) ---------- */
async function sendResetEmail(to, url) {
  if (!process.env.SMTP_HOST) {
    console.log(`[email disabled] password reset for ${to}: ${url}`);
    return;
  }
  const { default: nodemailer } = await import('nodemailer');
  const transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST,
    port: +(process.env.SMTP_PORT ?? 587),
    secure: process.env.SMTP_SECURE === 'true',
    auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS },
  });
  await transporter.sendMail({
    from: process.env.MAIL_FROM ?? 'SynthData <no-reply@testforge-ai.com>',
    to,
    subject: 'Reset your SynthData password',
    text: `Someone requested a password reset for your SynthData account.\n\nReset link (valid 1 hour):\n${url}\n\nIf this wasn't you, ignore this email.`,
    html: `<p>Someone requested a password reset for your SynthData account.</p>
           <p><a href="${url}">Reset your password</a> (valid 1 hour)</p>
           <p>If this wasn't you, ignore this email.</p>`,
  });
}

/* ---------- helpers ---------- */
const app = express();
app.use(express.json({ limit: '2mb' }));

const sign = (user) => jwt.sign({ id: user.id, email: user.email }, JWT_SECRET, { expiresIn: '7d' });
const publicUser = (u) => ({ id: u.id, email: u.email, name: u.name });

function auth(req, res, next) {
  const h = req.headers.authorization ?? '';
  const token = h.startsWith('Bearer ') ? h.slice(7) : null;
  if (!token) return res.status(401).json({ error: 'not logged in' });
  try { req.user = jwt.verify(token, JWT_SECRET); next(); }
  catch { res.status(401).json({ error: 'session expired — log in again' }); }
}

// simple in-memory rate limit for auth endpoints
const hits = new Map();
function limit(scope, max, windowMs) {
  return (req, res, next) => {
    const key = `${scope}:${req.ip}`;
    const now = Date.now();
    const arr = (hits.get(key) ?? []).filter(t => now - t < windowMs);
    if (arr.length >= max) return res.status(429).json({ error: 'too many attempts — try later' });
    arr.push(now); hits.set(key, arr); next();
  };
}

/* ---------- auth ---------- */
app.post('/api/auth/register', limit('reg', 10, 15 * 60_000), (req, res) => {
  const { email, password, name } = req.body ?? {};
  if (!email || !/^\S+@\S+\.\S+$/.test(email)) return res.status(400).json({ error: 'valid email required' });
  if (!password || password.length < 8) return res.status(400).json({ error: 'password must be at least 8 characters' });
  const id = crypto.randomUUID();
  try {
    db.prepare('INSERT INTO users (id, email, name, pass_hash) VALUES (?,?,?,?)')
      .run(id, email.toLowerCase(), name ?? null, hashPassword(password));
  } catch {
    return res.status(409).json({ error: 'an account with this email already exists' });
  }
  const user = db.prepare('SELECT * FROM users WHERE id = ?').get(id);
  res.status(201).json({ token: sign(user), user: publicUser(user) });
});

app.post('/api/auth/login', limit('login', 10, 15 * 60_000), (req, res) => {
  const { email, password } = req.body ?? {};
  const user = db.prepare('SELECT * FROM users WHERE email = ?').get((email ?? '').toLowerCase());
  if (!user || !verifyPassword(password ?? '', user.pass_hash))
    return res.status(401).json({ error: 'wrong email or password' });
  res.json({ token: sign(user), user: publicUser(user) });
});

app.post('/api/auth/forgot', limit('forgot', 5, 15 * 60_000), async (req, res) => {
  const { email } = req.body ?? {};
  const user = db.prepare('SELECT * FROM users WHERE email = ?').get((email ?? '').toLowerCase());
  if (user) {
    const token = crypto.randomBytes(32).toString('hex');
    db.prepare('INSERT INTO reset_tokens (token, user_id, expires_at) VALUES (?,?,?)')
      .run(token, user.id, Date.now() + 60 * 60_000);
    try { await sendResetEmail(user.email, `${PUBLIC_URL}/reset?token=${token}`); }
    catch (e) { console.error('email send failed:', e.message); }
  }
  // always generic — don't reveal whether the email exists
  res.json({ ok: true, message: 'If that email has an account, a reset link is on its way.' });
});

app.post('/api/auth/reset', limit('reset', 5, 15 * 60_000), (req, res) => {
  const { token, password } = req.body ?? {};
  if (!password || password.length < 8) return res.status(400).json({ error: 'password must be at least 8 characters' });
  const row = db.prepare('SELECT * FROM reset_tokens WHERE token = ? AND used = 0').get(token ?? '');
  if (!row || row.expires_at < Date.now()) return res.status(400).json({ error: 'invalid or expired reset link' });
  db.prepare('UPDATE users SET pass_hash = ? WHERE id = ?').run(hashPassword(password), row.user_id);
  db.prepare('UPDATE reset_tokens SET used = 1 WHERE token = ?').run(token);
  res.json({ ok: true, message: 'Password updated — you can log in now.' });
});

app.get('/api/me', auth, (req, res) => {
  const user = db.prepare('SELECT * FROM users WHERE id = ?').get(req.user.id);
  if (!user) return res.status(401).json({ error: 'account not found' });
  res.json({ user: publicUser(user) });
});

/* ---------- datasets ---------- */
app.post('/api/datasets', auth, (req, res) => {
  try {
    const { name, ddl, planYaml, businessCase, seed, rows } = req.body ?? {};
    if (!ddl) return res.status(400).json({ error: 'ddl is required' });
    const tables = parseDDL(ddl);
    const tableNames = Object.keys(tables);
    if (!tableNames.length) return res.status(400).json({ error: 'no CREATE TABLE statements found' });
    let plan_yaml = planYaml;
    if (!plan_yaml) {
      plan_yaml = YAML.stringify({ tables: Object.fromEntries(tableNames.map(t => [t, { rows: rows ?? 100 }])) });
    }
    const plan = YAML.parse(plan_yaml);
    const s = seed ?? plan.seed ?? 42;
    const data = new Engine(tables, plan, s).run();   // validates the recipe
    const rowsCount = Object.values(data).reduce((a, r) => a + r.length, 0);
    const id = crypto.randomUUID();
    db.prepare(`INSERT INTO datasets (id, user_id, name, ddl, business_case, plan_yaml, seed, tables_count, rows_count)
                VALUES (?,?,?,?,?,?,?,?,?)`)
      .run(id, req.user.id, name || `dataset-${id.slice(0, 8)}`, ddl, businessCase ?? null,
           plan_yaml, s, tableNames.length, rowsCount);
    res.status(201).json({ id, tables: tableNames.length, rows: rowsCount, seed: s });
  } catch (e) { res.status(422).json({ error: e.message }); }
});

app.get('/api/datasets', auth, (req, res) => {
  res.json({ datasets: db.prepare(
    `SELECT id, name, seed, tables_count, rows_count, created_at
     FROM datasets WHERE user_id = ? ORDER BY created_at DESC`).all(req.user.id) });
});

app.get('/api/datasets/:id/file', auth, (req, res) => {
  try {
    const row = db.prepare('SELECT * FROM datasets WHERE user_id = ? AND id = ?').get(req.user.id, req.params.id);
    if (!row) return res.status(404).json({ error: 'not found' });
    const tables = parseDDL(row.ddl);
    const data = new Engine(tables, YAML.parse(row.plan_yaml), row.seed).run();
    const format = String(req.query.format ?? 'db');
    if (format === 'sql') {
      const out = [];
      for (const [t, rows] of Object.entries(data))
        for (const r of rows) {
          const vals = Object.values(r).map(v => v == null ? 'NULL'
            : typeof v === 'number' ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
          out.push(`INSERT INTO ${t} (${Object.keys(r).join(',')}) VALUES (${vals.join(',')});`);
        }
      res.setHeader('Content-Disposition', `attachment; filename="${row.name}.sql"`);
      return res.send(out.join('\n'));
    }
    // .db — build in a temp file with better-sqlite3, stream back
    const tmp = path.join(DATA_DIR, `tmp-${crypto.randomUUID()}.db`);
    const out = new Database(tmp);
    out.pragma('foreign_keys = ON');
    out.exec(ddlToSqlite(row.ddl));
    const insertAll = out.transaction(() => {
      for (const [tname, rows] of Object.entries(data)) {
        if (!rows.length) continue;
        const cols = Object.keys(rows[0]);
        const stmt = out.prepare(`INSERT INTO ${tname} (${cols.join(',')}) VALUES (${cols.map(() => '?').join(',')})`);
        for (const r of rows) stmt.run(cols.map(c => r[c] ?? null));
      }
    });
    insertAll();
    out.close();
    res.setHeader('Content-Disposition', `attachment; filename="${row.name}.db"`);
    res.setHeader('Content-Type', 'application/octet-stream');
    res.send(fs.readFileSync(tmp));
    fs.unlinkSync(tmp);
  } catch (e) { res.status(422).json({ error: e.message }); }
});

app.delete('/api/datasets/:id', auth, (req, res) => {
  db.prepare('DELETE FROM datasets WHERE user_id = ? AND id = ?').run(req.user.id, req.params.id);
  res.status(204).end();
});

app.get('/api/health', (_req, res) => res.json({ ok: true }));

app.listen(PORT, '127.0.0.1', () => {
  console.log(`synthdata api on 127.0.0.1:${PORT} (data: ${DATA_DIR})`);
  if (JWT_SECRET === 'dev-secret-change-me') console.warn('WARNING: set JWT_SECRET in production!');
});
