// Exporters: CSV files, SQL insert script, SQLite .db (via sql.js WASM),
// and PostgreSQL load script.
import fs from 'node:fs';
import path from 'node:path';
import { topoOrder } from './schema.js';

export function toCsv(data, outDir) {
  fs.mkdirSync(outDir, { recursive: true });
  for (const [tname, rows] of Object.entries(data)) {
    if (!rows.length) continue;
    const cols = Object.keys(rows[0]);
    const esc = (v) => {
      if (v == null) return '';
      const s = String(v);
      return /[",\n]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s;
    };
    const lines = [cols.join(','), ...rows.map(r => cols.map(c => esc(r[c])).join(','))];
    fs.writeFileSync(path.join(outDir, `${tname}.csv`), lines.join('\n'), 'utf-8');
  }
}

const sqlVal = (v) => v == null ? 'NULL'
  : typeof v === 'number' ? String(v)
  : "'" + String(v).replace(/'/g, "''") + "'";

export function insertStatements(data) {
  const out = [];
  for (const [tname, rows] of Object.entries(data)) {
    for (const r of rows) {
      // meta columns (e.g. _violation from the negative profile) become comments,
      // so the INSERT itself stays runnable against the real schema
      const cols = Object.keys(r).filter(k => !k.startsWith('_'));
      const note = r._violation ? `  -- violation: ${r._violation}` : '';
      out.push(`INSERT INTO ${tname} (${cols.join(',')}) VALUES (${cols.map(c => sqlVal(r[c])).join(',')});${note}`);
    }
  }
  return out;
}

export function toSqlFile(data, filePath) {
  fs.writeFileSync(filePath, insertStatements(data).join('\n') + '\n', 'utf-8');
}

// ---- PostgreSQL export ----
// Emits one psql-loadable script: DDL + batched INSERTs in FK dependency
// order, wrapped in a single transaction. Handles what SQLite didn't need:
//   - OVERRIDING SYSTEM VALUE for GENERATED ALWAYS AS IDENTITY columns
//   - TRUE/FALSE literals for BOOLEAN columns (PG rejects 0/1 in inserts)
//   - setval() so identity sequences continue after the explicit IDs
const PG_BATCH = 500;

export function ddlToPostgres(ddl) {
  return ddl
    .replace(/\bAUTOINCREMENT\b/gi, '')       // SQLite-ism
    .replace(/\bDATETIME\b/gi, 'TIMESTAMP');  // SQLite/MySQL-ism
}

const pgVal = (v, isBool) => {
  if (v == null) return 'NULL';
  if (isBool) return (v === true || v === 1 || v === '1' || v === 'TRUE') ? 'TRUE' : 'FALSE';
  return typeof v === 'number' ? String(v) : "'" + String(v).replace(/'/g, "''") + "'";
};

export function toPostgresSql(ddl, tables, data, filePath, seed) {
  const lines = [
    '-- Generated by @vijaypjavvadi/synthdata' + (seed != null ? ` (seed=${seed})` : ''),
    `-- Load with: psql -d your_db -f ${path.basename(filePath)}`,
    '', 'BEGIN;', '', ddlToPostgres(ddl).trim(), '',
    '-- data (foreign-key dependency order)',
  ];
  const setvals = [];
  for (const tname of topoOrder(tables)) {
    const rows = data[tname];
    if (!rows || !rows.length) continue;
    const cols = Object.keys(rows[0]);
    const tcols = tables[tname].columns;
    const boolCols = new Set(tcols.filter(c => c.dtype.includes('BOOL')).map(c => c.name));
    const ov = tcols.some(c => c.identity && cols.includes(c.name)) ? ' OVERRIDING SYSTEM VALUE' : '';
    for (const c of tcols) {
      if (c.identity && cols.includes(c.name)) {
        setvals.push(`SELECT setval(pg_get_serial_sequence('${tname}', '${c.name}'), ` +
                     `COALESCE((SELECT MAX(${c.name}) FROM ${tname}), 1));`);
      }
    }
    lines.push(`\n-- ${tname}: ${rows.length} rows`);
    for (let i = 0; i < rows.length; i += PG_BATCH) {
      const chunk = rows.slice(i, i + PG_BATCH);
      lines.push(`INSERT INTO ${tname} (${cols.join(', ')})${ov} VALUES`);
      lines.push(chunk.map(r =>
        '  (' + cols.map(c => pgVal(r[c], boolCols.has(c))).join(', ') + ')').join(',\n') + ';');
    }
  }
  if (setvals.length) lines.push('\n-- resume identity sequences after explicit IDs', ...setvals);
  lines.push('', 'COMMIT;', '');
  fs.writeFileSync(filePath, lines.join('\n'), 'utf-8');
}

// Transpile our supported DDL subset to SQLite-compatible DDL.
export function ddlToSqlite(ddl) {
  return ddl
    .replace(/(BIGINT|INT|INTEGER)\s+GENERATED\s+ALWAYS\s+AS\s+IDENTITY/gi, 'INTEGER')
    .replace(/\bBOOLEAN\b/gi, 'INTEGER')
    .replace(/\bTIMESTAMP\b/gi, 'TEXT')
    .replace(/DEFAULT\s+CURRENT_TIMESTAMP/gi, "DEFAULT (datetime('now'))");
}

export async function toSqliteDb(ddl, data, dbPath) {
  const { default: initSqlJs } = await import('sql.js');
  const SQL = await initSqlJs();
  const db = new SQL.Database();
  db.run('PRAGMA foreign_keys = ON;');
  db.run(ddlToSqlite(ddl));
  for (const [tname, rows] of Object.entries(data)) {
    if (!rows.length) continue;
    const cols = Object.keys(rows[0]);
    const stmt = db.prepare(`INSERT INTO ${tname} (${cols.join(',')}) VALUES (${cols.map(() => '?').join(',')})`);
    db.run('BEGIN');
    for (const r of rows) stmt.run(cols.map(c => r[c] === undefined ? null : r[c]));
    db.run('COMMIT');
    stmt.free();
  }
  const violations = db.exec('PRAGMA foreign_key_check');
  fs.writeFileSync(dbPath, Buffer.from(db.export()));
  db.close();
  if (violations.length) throw new Error(`FK check failed: ${violations[0].values.length} violations`);
}
